"""add action_by_id in Friendship

Revision ID: 53ba808266d2
Revises: 7772369a765d
Create Date: 2026-03-06 19:32:57.124095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ba808266d2'
down_revision: Union[str, Sequence[str], None] = '7772369a765d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friendship', sa.Column('action_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'friendship', 'users', ['action_by_id'], ['id'])
    op.alter_column('posts', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.drop_column('friendship', 'action_by_id')
    # ### end Alembic commands ###
