"""fix

Revision ID: 5b47c8eeaa1b
Revises: fdbe92c6be3d
Create Date: 2026-02-24 13:37:22.625041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b47c8eeaa1b'
down_revision: Union[str, Sequence[str], None] = 'fdbe92c6be3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='expires_at::timestamp with time zone'
               )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
