"""change comment model

Revision ID: 853207af23ac
Revises: d3326b0b2588
Create Date: 2026-03-02 15:57:46.269607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '853207af23ac'
down_revision: Union[str, Sequence[str], None] = 'd3326b0b2588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('comments', 'body')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'content')
    # ### end Alembic commands ###
