"""test

Revision ID: beb201f13bd7
Revises: 3c88213e57bb
Create Date: 2026-03-02 08:46:15.715269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb201f13bd7'
down_revision: Union[str, Sequence[str], None] = '3c88213e57bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('posts', 'body')
    op.drop_column('posts', 'title')
    op.drop_column('posts', 'is_published')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=True)
    op.add_column('posts', sa.Column('is_published', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('posts', sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###
