"""fix relations

Revision ID: e3180f9a3bfe
Revises: d52eb96ec340
Create Date: 2026-03-16 16:32:20.879875

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'e3180f9a3bfe'
down_revision: Union[str, Sequence[str], None] = 'd52eb96ec340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('friendship_action_by_id_fkey'), 'friendship', type_='foreignkey')
    op.create_unique_constraint('uq_oauth_providers_provider', 'oauth_providers', ['provider'])
    op.create_foreign_key(None, 'friendship', 'users', ['action_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'friendship', type_='foreignkey')
    op.create_foreign_key(op.f('friendship_action_by_id_fkey'), 'friendship', 'users', ['action_by_id'], ['id'])
    # ### end Alembic commands ###
