"""add providers table

Revision ID: f869c6f67773
Revises: 50926ca41f8b
Create Date: 2026-02-23 14:04:42.964627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f869c6f67773'
down_revision: Union[str, Sequence[str], None] = '50926ca41f8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('oauth_accounts', sa.Column('provider_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('oauth_accounts_provider_user_id_key'), 'oauth_accounts', type_='unique')
    op.create_foreign_key(None, 'oauth_accounts', 'oauth_providers', ['provider_id'], ['id'])
    op.drop_column('oauth_accounts', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('provider', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'oauth_accounts', type_='foreignkey')
    op.create_unique_constraint(op.f('oauth_accounts_provider_user_id_key'), 'oauth_accounts', ['provider_user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('oauth_accounts', 'provider_id')
    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
